### PR TITLE
Deprecate swagger-node-express, import swagger-node

### PR DESCRIPTION
**Pull request by theganyo**
This PR deletes all existing files in swagger-node-express and imports all the files from swagger-node, maintaining history for both. The new project is a CLI that creates and manages connect, express, sails, hapi, and restify projects using Swagger 2.0. This project is intended to be published to npmjs as "swagger" - replacing the existing "swagger-node" project there that will be deprecated and removed.

### CODE REVIEW

**Comment by fehguy** [comment]
Thanks @theganyo!  Working on the merge and supporting upgrade notes.

**Comment by theganyo** [comment]
Thanks, @fehguy!

**Comment by DaniloOliveira28** [comment]
It looks like a great initiative. Ty @theganyo  and @fehguy for the work!

However I feeling lost with all these changes, I was using the old swagger-node-express in my projects. What repo I need to follow? I found three with similar code:

https://github.com/apigee-127/swagger-node
https://github.com/apigee-127/swagger-express
https://github.com/swagger-api/swagger-node

What is the objective of each one?

Thanks

**Comment by theganyo** [comment]
Sorry it's confusing. We clearly need to do a better job of explaining how the pieces fit together. 

But to answer your question:

The first repo will be going away with the move.

The second provides middleware to a swagger-node app using express.

The third is the primary repo for the swagger-node toolkit now. It is the CLI that creates and manages project and provides other tools for Swagger such as validating a specification doc.

**Comment by webron** [comment]
@theganyo - if this one replaces the one at a127, perhaps until that one is removed, add a clear note at the top of the project's README that it has moved here?

**Comment by theganyo** [comment]
Done!

**Comment by prabhatjha** [comment]
I think we should also delete the swagger-node repo from apigee-127 org.
WDYT?

On Sun, Jun 7, 2015 at 10:34 AM, Scott Ganyo <notifications@github.com>
wrote:

> Done!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-node/pull/207#issuecomment-109779050>
> .
>



-- 
Cheers,
Prabhat
---------------------------
Help spread www.eejot.org

**Comment by theganyo** [comment]
Yes, that's what I said above. However, until we release a new version to npmjs, we still have a link that points at the apigee-127. This will be very soon, but not now.

**Comment by webron** [comment]
Since we didn't do a project transfer, but merge the code, I'd suggested not deleting the repo for a few months but emptying it from content, leaving a readme explaining the project have moved here and put a link. 

This would allow for previous users to follow the link more easily.

**Pull request merged**
